plugins { id "com.android.application" }
android {
 namespace "com.agtstudio.productai"
 compileSdk 35
 defaultConfig {
   applicationId "com.agtstudio.productai.test"
   minSdk 24
   targetSdk 35
   versionCode 41
   versionName "1.0.41"
 }
 buildFeatures { buildConfig true }
 buildTypes { release { minifyEnabled false; shrinkResources false } }
}
dependencies { implementation "androidx.webkit:webkit:1.12.1"; implementation "androidx.core:core:1.15.0" }