const RECIPES={
 hero:['Satışa Hazır','🛍️','1:1','Create a premium commercial e-commerce product image. Preserve the exact reference product identity, geometry, proportions, materials, colors, labels, logos and all visible details. Make the product the clear hero subject, large and sharply recognizable. Clean professional composition, realistic studio lighting, natural contact shadow. No people, hands, body parts, invented features, text, badges or watermark.'],
 cinematic:['Sinematik','🎬','4:5','Create a cinematic premium commercial product photograph from the supplied reference. Preserve exact product identity, geometry, proportions, materials, colors, labels, logos and visible details. Use dramatic but realistic cinematic lighting, rich depth, tasteful environment and sophisticated editorial composition. Product remains dominant. No people, hands, body parts, invented features, text or watermark.'],
 clean:['Sade Ortam','🧼','1:1','Create a clean minimalist commercial product photograph from the supplied reference. Preserve exact product identity, geometry, proportions, materials, colors and visible details. Simple uncluttered neutral environment, soft natural light, subtle realistic shadow, premium realistic product photography. No people, competing props, invented features, text or watermark.'],
 studio:['Premium Stüdyo','✨','4:5','Create a high-end professional studio product photograph from the supplied reference. Preserve exact product identity, geometry, proportions, materials, colors, labels and visible details. Controlled softbox lighting, refined neutral studio background and realistic grounding shadow. No people, hands, body parts, invented features, text or watermark.'],
 lifestyle:['Lifestyle','🏠','4:5','Create a premium lifestyle product photograph from the supplied reference. Preserve exact product identity, geometry, proportions, materials, colors and visible details. Place it naturally in a tasteful modern environment relevant to its category with realistic daylight and restrained decor. Product is the clear hero. No people, hands, body parts, invented features, text or watermark.'],
 social:['Sosyal Medya','📱','4:5','Create a polished social-media-ready commercial product visual from the supplied reference. Preserve exact product identity, geometry, proportions, materials, colors, labels and visible details. Attractive editorial composition, strong product focus, realistic lighting and intentional negative space. No people, invented features, text, badges or watermark.']
};
const PROVIDERS=[
 ['aihorde','AI Horde','🌐',true,false,'AlbedoBase XL (SDXL)'],
 ['pollinations','Pollinations','⚡',true,true,'qwen-image-3'],
 ['gemini','Google Gemini','✨',false,true,'gemini-3.1-flash-image'],
 ['openai','OpenAI','◉',false,true,'gpt-image-1'],
 ['cloudflare','Cloudflare AI','☁️',false,true,'@cf/runwayml/stable-diffusion-v1-5-img2img'],
 ['custom','Özel OpenAI','🔌',false,true,''],
 ['comfyui','Yerel ComfyUI','🖥️',true,false,'Qwen Image Edit'],
 ['generic','OpenAI uyumlu / Özel API','🔗',false,true,'']
];
let state={file:null,recipe:'hero',slots:read('provider-slots')||[],selected:null,mode:read('provider-mode')||'free',count:1,ratio:'1:1',busy:false,results:[],extra:''};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const provider=id=>PROVIDERS.find(p=>p[0]===id);
function read(k){try{if(window.AGTNativeVault){const v=window.AGTNativeVault.get(k);return v?JSON.parse(v):null}}catch(e){}try{return JSON.parse(localStorage.getItem(k)||'null')}catch(e){return null}}
function write(k,v){try{if(window.AGTNativeVault){window.AGTNativeVault.set(k,JSON.stringify(v));return}}catch(e){}try{localStorage.setItem(k,JSON.stringify(v))}catch(e){}}
function promptText(){return RECIPES[state.recipe][3]+(state.extra.trim()?' Additional direction: '+state.extra.trim():'')}
function message(t,type=''){const e=$('#status');if(e){e.textContent=t;e.className='status '+type}}
function render(){
 const connected=state.slots.length;
 $('#app').innerHTML=`<div class="shell">
 <header><div class="brand"><b>AGT</b><span>Studio <small>PRODUCT AI</small></span></div><div class="header-right"><span>${connected} AI bağlı</span><button id="settings">Ayarlar</button></div></header>
 <section class="hero"><div><label>AGT PRODUCT AI</label><h1>Ürününü<br><i>satışa hazırla.</i></h1><p>AI'ı sen bağla. Reçeteyi AGT hazırlasın. Görseller doğrudan senin AI hesabınla üretilir.</p><div class="trust">✓ Sunucu yok &nbsp; ✓ Anahtar cihazda &nbsp; ✓ Sınırsız AI bağlantısı</div></div><div class="upload" id="upload"><input id="file" type="file" accept="image/jpeg,image/png,image/webp"><div class="plus">＋</div><b id="fname">Ürün fotoğrafını yükle</b><small>JPG, PNG veya WEBP · Maks. 12 MB</small><button id="pick">Dosya seç</button></div></section>
 <section class="card"><div class="section-head"><div><label>01 · REÇETE</label><h2>Nasıl bir görsel?</h2></div><small>Prompt otomatik hazırlanır</small></div><div class="recipes" id="recipes"></div><label class="extra">Ek tercih <em>opsiyonel</em><textarea id="extra" maxlength="500" placeholder="Örn. krem tonları, mermer yüzey, yumuşak gün ışığı…">${esc(state.extra)}</textarea></label></section>
 <section class="card"><div class="section-head"><div><label>02 · AI MOTORU</label><h2>AI bağlantını seç</h2></div><button id="add">＋ AI bağla</button></div><div class="slots" id="slots"></div><div class="auto"><span>⚙️</span><div><b>AI seçim yöntemi</b><small id="strategyText"></small></div><select id="strategy"><option value="free">Ücretsiz öncelikli</option><option value="paid">Ücretli öncelikli</option><option value="manual">Ben seçeyim</option></select></div></section>
 <section class="card"><div class="section-head"><div><label>03 · ÜRETİM</label><h2>Son dokunuş</h2></div></div><div class="controls"><label>Görsel sayısı<select id="count"><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option></select></label><label>Görsel oranı<select id="ratio"><option>1:1</option><option>4:5</option><option>16:9</option><option>9:16</option></select></label></div><button class="generate" id="generate">✦ &nbsp; ${state.busy?'Görsel hazırlanıyor…':'Görselleri Üret'} <b>→</b></button><div id="status"></div></section>
 <section class="card" id="resultsCard" style="display:${state.results.length?'block':'none'}"><div class="section-head"><div><label>SONUÇ</label><h2>${state.results.length} görsel hazır</h2></div></div><div class="results" id="results"></div></section>
 </div><div class="modal hidden" id="modal"><div class="modal-box"><div class="section-head"><div><label>AI BAĞLANTISI</label><h2>AI ekle</h2></div><button id="close">×</button></div><div class="provider-pick" id="providerPick"></div><div id="form"></div></div></div>`;
 $('#count').value=state.count;$('#ratio').value=state.ratio;$('#strategy').value=state.mode;
 renderRecipes();renderSlots();renderResults();bind();
}
function renderRecipes(){const box=$('#recipes');Object.entries(RECIPES).forEach(([id,r])=>{const b=document.createElement('button');b.className='recipe '+(state.recipe===id?'active':'');b.dataset.r=id;b.innerHTML='<strong>'+r[1]+'</strong><b>'+r[0]+'</b><small>'+r[2]+'</small>';b.onclick=()=>{state.recipe=id;state.ratio=r[2];render()};box.appendChild(b)})}
function renderSlots(){const box=$('#slots');if(!state.slots.length){box.innerHTML='<div class="empty"><b>Henüz AI bağlanmadı</b><small>İlk bağlantını ekle. Ücretsiz motorlar otomatik önceliklidir.</small><button class="primary" id="emptyAdd">İlk AI\'ı bağla</button></div>';$('#emptyAdd').onclick=openModal}else{state.slots.forEach(s=>{const p=provider(s.provider);if(!p)return;const b=document.createElement('button');b.className='slot '+(state.mode==='manual'&&state.selected===s.id?'active':'');b.innerHTML='<span>'+p[2]+'</span><div><b>'+esc(s.label||p[1])+'</b><small>'+p[1]+' · '+esc(s.model||p[5]||'Hazır')+'</small></div><i>'+(p[3]?'ÜCRETSİZ':'BAĞLI')+'</i>';b.onclick=()=>{state.selected=s.id;state.mode='manual';write('provider-mode',state.mode);render()};box.appendChild(b)})}$('#strategyText').textContent=state.mode==='free'?'Ücretsiz motorları önce dener; gerekirse ücretliye geçer.':state.mode==='paid'?'Ücretli/kendi API motorlarını önce dener; gerekirse ücretsizlere geçer.':'Bağladığın AI motorlarından birini sen seçersin.'}
function renderResults(){const box=$('#results');if(!box)return;box.innerHTML='';state.results.forEach((x,i)=>{const f=document.createElement('figure');const img=document.createElement('img');img.src=x.url;const b=document.createElement('button');b.textContent='İndir';b.onclick=()=>download(x,i);f.append(img,b);box.appendChild(f)})}
function bind(){$('#pick').onclick=e=>{e.stopPropagation();$('#file').click()};$('#upload').onclick=e=>{if(e.target.id!=='pick')$('#file').click()};$('#file').onchange=e=>{const f=e.target.files&&e.target.files[0];if(!f)return;if(!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>12582912){message('Geçersiz görsel. JPG/PNG/WEBP ve 12 MB sınırı.','error');return}state.file=f;state.results=[];render();$('#fname').textContent='✓ '+f.name};$('#extra').oninput=e=>state.extra=e.target.value;$('#count').onchange=e=>state.count=Number(e.target.value);$('#ratio').onchange=e=>state.ratio=e.target.value;$('#strategy').onchange=e=>{state.mode=e.target.value;state.selected=null;write('provider-mode',state.mode);render()};$('#add').onclick=openModal;$('#settings').onclick=openModal;$('#generate').onclick=generate}
function openModal(){$('#modal').classList.remove('hidden');$('#close').onclick=()=>$('#modal').classList.add('hidden');const box=$('#providerPick');box.innerHTML='';PROVIDERS.forEach(p=>{const b=document.createElement('button');b.dataset.p=p[0];b.innerHTML='<strong>'+p[2]+'</strong><b>'+p[1]+'</b><small>'+(p[3]?'Ücretsiz seçenek':'Ücretli / kendi API anahtarın')+'</small>';b.onclick=()=>showForm(p[0]);box.appendChild(b)})}
function showForm(pid){const p=provider(pid),old=state.slots.find(x=>x.provider===pid);let html='<div class="form"><h3>'+p[2]+' '+p[1]+'</h3><p>API anahtarı yalnızca bu cihazda tutulur. Yerel ComfyUI için internet gerekmez.</p><label>Bağlantı adı<input id="label" value="'+esc(old?.label||p[1])+'"></label>';
 if(p[4])html+='<label>API Key<input id="key" type="password" placeholder="API anahtarını gir" autocomplete="off"></label>';
 if(pid==='cloudflare')html+='<label>Account ID<input id="account" value="'+esc(old?.accountId||'')+'"></label>';
 if(['custom','comfyui','generic'].includes(pid))html+='<label>Base URL<input id="base" value="'+esc(old?.baseUrl||(pid==='comfyui'?'http://127.0.0.1:8188':''))+'" placeholder="https://.../v1"></label>';
 if(pid==='comfyui')html+='<label>ComfyUI API Workflow JSON<textarea id="workflow" placeholder="ComfyUI → Save (API Format) çıktısını buraya yapıştır">'+esc(old?.workflow||'')+'</textarea></label>';
 if(pid==='generic')html+='<small class="note">OpenAI uyumlu görsel API için endpoint + anahtar + model gir.</small>';
 html+='<label>Model<input id="model" value="'+esc(old?.model||p[5])+'"></label><button class="primary" id="save">Bağlantıyı kaydet</button><small class="note">🔒 Anahtar ekranda tekrar gösterilmez.</small></div>';
 $('#form').innerHTML=html;$('#providerPick').style.display='none';$('#save').onclick=()=>saveProvider(pid,old,p)}
function saveProvider(pid,old,p){const key=$('#key')?.value.trim()||old?.key||'';if(p[4]&&!key){message('API anahtarı gerekli.','error');return}const n={id:old?.id||crypto.randomUUID(),provider:pid,label:$('#label').value.trim()||p[1],key,model:$('#model').value.trim()||p[5],baseUrl:$('#base')?.value.trim()||old?.baseUrl||'',accountId:$('#account')?.value.trim()||old?.accountId||'',workflow:$('#workflow')?.value||old?.workflow||''};state.slots=old?state.slots.map(x=>x.id===n.id?n:x):state.slots.concat(n);write('provider-slots',state.slots);state.selected=n.id;state.mode='manual';write('provider-mode',state.mode);$('#modal').classList.add('hidden');render()}
async function generate(){if(!state.file||state.busy)return;let list;if(state.mode==='free')list=[...state.slots].sort((a,b)=>Number(provider(b.provider)?.[3])-Number(provider(a.provider)?.[3]));else if(state.mode==='paid')list=[...state.slots].sort((a,b)=>Number(provider(a.provider)?.[3])-Number(provider(b.provider)?.[3]));else list=[state.slots.find(x=>x.id===state.selected)].filter(Boolean);if(!list.length){message(state.mode==='manual'?'Önce bir AI motoru seç.':'Önce en az bir AI bağlantısı ekle.','error');return}state.busy=true;render();let last='';for(const s of list){try{message('Görsel hazırlanıyor…');state.results=await callProvider(s);state.busy=false;render();message('Görsel hazır.','success');return}catch(e){last=e.message||String(e)}}state.busy=false;render();message('Üretim tamamlanamadı: '+last,'error')}
async function callProvider(s){const p=promptText();if(s.provider==='gemini'){const source=await b64(state.file);const r=await fetch('https://generativelanguage.googleapis.com/v1/models/'+encodeURIComponent(s.model)+':generateContent',{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':s.key},body:JSON.stringify({contents:[{role:'user',parts:[{inlineData:{mimeType:state.file.type,data:source}},{text:p}]}],generationConfig:{responseModalities:['IMAGE']}})});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||'Gemini API hatası');const x=(d?.candidates?.[0]?.content?.parts||[]).find(v=>v.inlineData?.data)?.inlineData;if(!x)throw Error('Gemini görsel döndürmedi');return[{url:'data:'+x.mimeType+';base64,'+x.data}]}
 if(['openai','custom','generic'].includes(s.provider)){const fd=new FormData();fd.append('model',s.model);fd.append('prompt',p);fd.append('n',String(state.count));fd.append('size',state.ratio==='4:5'?'1024x1280':'1024x1024');fd.append('image',state.file,state.file.name);const base=(s.baseUrl||'https://api.openai.com/v1').replace(/\/$/,'');const r=await fetch(base+'/images/edits',{method:'POST',headers:s.key?{Authorization:'Bearer '+s.key}:{},body:fd});const d=await r.json();if(!r.ok)throw Error(d?.error?.message||'OpenAI uyumlu API hatası');return(d.data||[]).map(x=>({url:x.b64_json?'data:image/png;base64,'+x.b64_json:x.url}))}
 if(s.provider==='pollinations'){const u='https://image.pollinations.ai/prompt/'+encodeURIComponent(p)+'?model='+encodeURIComponent(s.model||'flux')+'&width=768&height=768&nologo=true';const r=await fetch(u);if(!r.ok)throw Error('Pollinations API hatası');return[{url:URL.createObjectURL(await r.blob())}]}
 if(s.provider==='aihorde'){const source=await b64(state.file);const r=await fetch('https://aihorde.net/api/v2/generate/async',{method:'POST',headers:{'Content-Type':'application/json',apikey:s.key||'0000000000'},body:JSON.stringify({prompt:p+' ### people, hands, body parts, duplicate product, altered geometry, text, watermark, blurry, low quality',models:[s.model||'AlbedoBase XL (SDXL)'],source_image:source,source_processing:'img2img',params:{width:1024,height:state.ratio==='4:5'?1280:1024,steps:30,n:1,cfg_scale:7.5,denoising_strength:.65},nsfw:false,censor_nsfw:true,r2:true,shared:false})});const d=await r.json();if(!r.ok||!d.id)throw Error(d?.message||'AI Horde isteği başarısız');for(let i=0;i<50;i++){await wait(1800);const q=await fetch('https://aihorde.net/api/v2/generate/check/'+encodeURIComponent(d.id),{headers:{apikey:s.key||'0000000000'}}).then(x=>x.json());if(q.faulted)throw Error(q.message||'AI Horde üretimi başarısız');if(q.done){const z=await fetch('https://aihorde.net/api/v2/generate/status/'+encodeURIComponent(d.id),{headers:{apikey:s.key||'0000000000'}}).then(x=>x.json()),g=z?.generations?.[0];if(!g?.img)throw Error('AI Horde görsel döndürmedi');return[{url:g.img}]}}throw Error('AI Horde kuyruğu zaman aşımına uğradı')}
 if(s.provider==='cloudflare'){if(!s.key||!s.accountId)throw Error('Cloudflare Account ID ve API Token gerekli');const r=await fetch('https://api.cloudflare.com/client/v4/accounts/'+encodeURIComponent(s.accountId)+'/ai/run/'+encodeURIComponent(s.model),{method:'POST',headers:{Authorization:'Bearer '+s.key,'Content-Type':'application/json'},body:JSON.stringify({image_b64:await b64(state.file),prompt:p})});const d=await r.json();if(!r.ok||!d.success)throw Error(d?.errors?.[0]?.message||'Cloudflare AI hatası');const x=d.result?.image||d.result?.output_image||d.result?.image_b64;if(!x)throw Error('Cloudflare görsel döndürmedi');return[{url:String(x).startsWith('data:')?String(x):'data:image/png;base64,'+x}]}
 if(s.provider==='comfyui')throw Error('ComfyUI bağlantısı uygulamanın masaüstü sürümünde kullanılmalıdır.');
 throw Error('Desteklenmeyen AI motoru')}
function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function b64(f){return toData(f).then(v=>String(v).split(',')[1])}
function toData(f){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(f)})}
function download(x,i){const a=document.createElement('a');a.href=x.url;a.download='AGT-'+String(i+1).padStart(2,'0')+'.png';document.body.appendChild(a);a.click();a.remove()}
render();